<?php
$group_name = $this->formText('group_name', '', array('class' => 'form-control col-xs-3', 'placeholder' => 'Type group name..'));
$avatar = $this->formFile('avatar', array('class' => ''));
$ranking = $this->formFile('ranking', array('class' => ''));
$options = array(' No', ' Yes');
$group_acp = $this->formRadio('group_acp', 0, NULL, $options, ' ');
$group_default = $this->formRadio('group_default', 0, NULL, $options, ' ');
$options = array(' InActive', ' Active');
$status = $this->formRadio('status', 0, NULL, $options, ' ');
$order = $this->formText('order', '', array('class' => 'form-control col-xs-3', 'placeholder' => 'Type order number..'));
?>
<form action="" method="POST" name="appForm">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <?php echo $this->render('group/toolbar/index.php'); ?>
                <div class="box-body table-responsive padding">

                    <div class="form-group col-xs-12">
                        <label class="col-sm-2 control-label" for="group_name">Group Name</label>
                        <div class="col-sm-3">
                            <?php echo $group_name ?>
                        </div>
                    </div>

                    <div class="form-group col-xs-12">
                        <label class="col-sm-2 control-label" for="avatar">Avatar</label>
                        <div class="col-sm-10">
                            <?php echo $avatar ?>
                        </div>
                    </div>

                    <div class="form-group col-xs-12">
                        <label class="col-sm-2 control-label" for="ranking">Ranking</label>
                        <div class="col-sm-10">
                            <?php echo $ranking ?>
                        </div>
                    </div>

                    <div class="form-group col-xs-12">
                        <label class="col-sm-2 control-label" for="group_acp">Admin Control Panel</label>
                        <div class="col-sm-10">
                            <?php echo $group_acp ?>
                        </div>
                    </div>

                    <div class="form-group col-xs-12">
                        <label class="col-sm-2 control-label" for="group_acp">Group Default</label>
                        <div class="col-sm-10">
                            <?php echo $group_default ?>
                        </div>
                    </div>
                    
                    <div class="form-group col-xs-12">
                        <label class="col-sm-2 control-label" for="group_acp">Status</label>
                        <div class="col-sm-10">
                            <?php echo $status ?>
                        </div>
                    </div>

                    <div class="form-group col-xs-12">
                        <label class="col-sm-2 control-label" for="group_acp">Order</label>
                        <div class="col-sm-3">
                            <?php echo $order ?>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</form>