<form action="" method="POST" name="appForm">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <?php echo $this->render('group/toolbar/index.php'); ?>
                <div class="box-body table-responsive padding">
                    <div class="alert alert-warning alert-dismissable">
                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                        <strong>This action can not be restored !</strong> Are you sure you want to delete this group?
                    </div>
                </div>
            </div>
        </div><!-- /.col -->
    </div>
</form>