<?php echo $this->render('html/header.php'); ?>
<?php echo $this->render('html/left-sidebar.php'); ?>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            <?php echo $this->title ?>
        </h1>
<!--        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
            <li class="active">Here</li>
        </ol>-->
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Your Page Content Here -->
        <?php echo $this->layout()->content ?>
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<?php echo $this->render("html/footer.php"); ?>
<?php
echo $this->render("html/right-sidebar.php");
